main/apps/log_reg/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
]

main/apps/schedules/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', home, name = "home"),
    url(r'^add$', add, name='add'),
    url(r'^add_trip$', add_trip, name='add_trip'),
    url(r'^join/(?P<id>\d+)$', join, name='join'),
    url(r'^destination/(?P<id>\d+)$', destination, name='destination'),
    url(r'^leave_trip/(?P<id>\d+)$', leave_trip, name='leave_trip'),
    url(r'^delete_trip/(?P<id>\d+)$', delete_trip, name='delete_trip'),
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.log_reg.urls', namespace= 'users')),
    url(r'^travels/', include('apps.schedules.urls', namespace='schedules'))
]

main/apps/schedules/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
from ..log_reg.models import *
import re
import datetime

destination_regex = re.compile(r'^[a-zA-Z -,.]+$')

class TripManager(models.Manager):
    def add_trip(self, form_data, request):
        valid = True
        user = User.objects.get(username = request.session['username'])
        destination = form_data['destination']
        description = form_data['description']
        date_from = form_data['date_from']
        date_to =form_data['date_to']
        if not destination_regex.match(form_data['destination']):
            messages.warning(request, "Destinations must be comprised of all letters, and no apostrophes!")
            valid = False
        if len(form_data['destination'])<1:
            messages.error(request, "Destination can not be blank. No drifting in the wind!")
            valid = False
        if len(form_data['description'])<1:
            messages.error(request, "Description can not be blank!")
            valid = False
        if not form_data['date_from'] or not form_data['date_to']:
            messages.error(request, "Dates range must be provided. No drifting in the wind!")
            valid = False
        if form_data['date_to'] < form_data['date_from']:
            messages.error(request, "End date can not be before start date!")
            valid = False
        if form_data['date_from'] < str(datetime.date.today()):
            messages.error(request, "Start date can not be before current date. No timeturners here!")
            valid = False
        if valid == True:
            Trip.objects.create(destination=destination, description=description, date_from=date_from, date_to=date_to, user_creator=user)
            print request.session['name'] + " added a trip to " + form_data['destination']
        return valid

    def join(self, id, request):
        print request.session['name'] + " is joining the trip to " + Trip.objects.get(id=id).destination
        this_user = User.objects.get(id=request.session['user_id'])
        this_trip = Trip.objects.get(id=id)
        this_trip.user_joiner.add(this_user)

    def leave_trip(self, id, request):
        print request.session['name'] + " is leaving the trip to " + Trip.objects.get(id=id).destination
        this_user = User.objects.get(id=request.session['user_id'])
        this_trip = Trip.objects.get(id=id)
        this_trip.user_joiner.remove(this_user)

    def delete_trip(self, id, request):
        trip = Trip.objects.get(id=id)
        valid = True
        if not trip.user_creator_id == request.session['user_id']:
            messages.error(request, "You're not the creator of this trip, so you can't delete it. Please email creator for them to remove you manually.")
            valid = False
        else:
            trip.delete()
            print "Sucessfully deleted trip " + id
        return valid

class Trip(models.Model):
    destination = models.CharField(max_length=500)
    description = models.CharField(max_length=500)
    date_from = models.DateField()
    date_to = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    user_creator= models.ForeignKey(User, related_name="user_create")
    user_joiner = models.ManyToManyField(User, related_name="user_join")
    objects = TripManager()

    def __str__(self):
        return self.destination

main/apps/schedules/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Count
from django.core.urlresolvers import reverse
from django.contrib import messages

def home(request):
    if not 'name' in request.session:
        return redirect('users:index')
    else:
        context = {
            'my_trips_created':Trip.objects.filter(user_creator=request.session['user_id']),
            'my_trips_joined':Trip.objects.filter(user_joiner=request.session['user_id']),
            'other_trips':Trip.objects.exclude(user_creator=request.session['user_id']).exclude(user_joiner=request.session['user_id']).order_by('date_from')
        }
        return render(request, 'schedules/home.html', context)

def add(request):
    if not 'name' in request.session:
        return redirect('users:index')
    else:
        return render(request, 'schedules/add.html')

def add_trip(request):
    if not 'name' in request.session:
        return redirect('users:index')
    else:
        if Trip.objects.add_trip(request.POST, request):
            valid = True
            print "Successful in adding trip to " + request.POST['destination']
            return redirect(reverse('schedules:home'))
        else:
            valid = False
            print "Unsuccessful in adding trip to " + request.POST['destination']
            return redirect(reverse('schedules:add'))

def join(request, id):
    if not 'name' in request.session:
        return redirect('users:index')
    Trip.objects.join(id, request)
    print request.session['name'] + " is joining the trip"
    return redirect(reverse('schedules:home'))

def destination(request, id):
    if not 'name' in request.session:
        return redirect('users:index')
    else:
        context = {
            'trips':Trip.objects.filter(id=id),
        }
        return render(request, 'schedules/destinations.html', context)

def leave_trip(request, id):
    if not 'name' in request.session:
        return redirect('users:index')
    Trip.objects.leave_trip(id, request)
    return redirect(reverse('schedules:home'))


def delete_trip(request, id):
    if not 'name' in request.session:
        return redirect('users:index')
    else:
        if Trip.objects.delete_trip(id, request):
            valid = True
            print "Deleting trip " + id
        else:
            print "Unable to delete trip " + id
    return redirect(reverse('schedules:home'))

main/apps/schedules/templates/schedules/add.html
<!DOCTYPE html>
<html>
   <head>
      <title>PY Belt</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'schedules/css/stylesheet.css' %}">
   </head>
   <div class="container">
      <header>
         <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'schedules:home' %}">Home</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
         </ul>
      </header>
      <body>
         <div class="wrapper">
            {% if messages %}
               {% for message in messages %}
               <div class="alert alert-info" role="alert">
                  <p>{{  message  }}</p>
               </div>
               {% endfor %}
            {% endif %}

            <div class="row">
            <div class="col-md-6">

               <h2>Add a Trip</h2>
               <form class="" action="{% url 'schedules:add_trip' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                     <label for="destination">Destination:</label>
                     <input name="destination" type="text" class="form-control" id="destination" placeholder="">
                  </div>

                  <div class="form-group">
                     <label for="description">Description:</label>
                     <input name="description" type="text" class="form-control" id="description" placeholder="">
                  </div>

                  <div class="form-group">
                     <label for="date_from">Travel Date From:</label>
                     <input name="date_from" type="date" class="form-control" id="date_from">
                  </div>

                  <div class="form-group">
                     <label for="date_to">Travel Date To:</label>
                     <input name="date_to" type="date" class="form-control" id="date_to">
                  </div>
                  <br>
                  <button type="submit" name="Add" class="btn btn-default">Add</button>
               </form>
            </div>
         </div>

            </div>
      </body>
   </div>
</html>

main/apps/schedules/templates/schedules/destinations.html
<!DOCTYPE html>
<html>
   <head>
      <title>PY Belt</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'schedules/css/stylesheet.css' %}">
   </head>
   <div class="container">
      <header>
         <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'schedules:home' %}">Home</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
         </ul>
      </header>
      <body>
         <div class="wrapper">
            {% if messages %}
               {% for message in messages %}
               <div class="alert alert-info" role="alert">
                  <p>{{  message  }}</p>
               </div>
               {% endfor %}
            {% endif %}

            <div class="row">
            <div class="col-md-6">
            {% for trip in trips %}
            <h2>{{  trip.destination  }}</h2>
            <ul>
               <li>Planned By: {{  trip.user_creator.name  }}</li>
               <li>Description: {{  trip.description  }}</li>
               <li>Travel Date From: {{  trip.date_from  }}</li>
               <li>Travel Date To: {{  trip.date_to  }}</li>
            </ul>
            <br><br>
            <h2>Other users' joining the trip:</h2>
            <ul>
               {% for user in trip.user_joiner.all %}
                  <li>{{  user.name  }}</li>
               {% endfor %}
            {% endfor %}
            </ul>
         </div>
      </div>

         </div>
   </body>
</div>
</html>

main/apps/schedules/templates/schedules/home.html
<!DOCTYPE html>
<html>
   <head>
      <title>PY Belt</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'schedules/css/stylesheet.css' %}">
   </head>
   <div class="container">
      <header>
         <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'schedules:home' %}">Home</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
         </ul>
      </header>
      <body>
         <div class="wrapper">
            <h1>Welcome, {{request.session.name}}!</h1>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
               <p>{{  message  }}</p>
            </div>
            {% endfor %}
            {% endif %}
            <br>
            <h4>Your Trip Schedule:</h4>
            <table class="table table-striped">
               <thead>
                  <tr>
                     <th>Destination</th>
                     <th>Travel Start Date</th>
                     <th>Travel End Date</th>
                     <th>Plan</th>
                     <th>Actions</th>
                  </tr>
               </thead>
               <tbody>
               {% for trip in my_trips_created %}
                  <tr>
                     <td><a href="{%  url 'schedules:destination' id=trip.id %}"> {{  trip.destination  }}</a></td>
                     <td>{{  trip.date_from  }}</td>
                     <td>{{  trip.date_to  }}</td>
                     <td>{{  trip.description  }}</td>
                     <td><a href="{%  url 'schedules:delete_trip' id=trip.id %}"> Delete Trip</a></td>
                  </tr>
               {% endfor %}
               {% for trip in my_trips_joined %}
                  <tr>
                     <td><a href="{%  url 'schedules:destination' id=trip.id %}"> {{  trip.destination  }}</a></td>
                     <td>{{  trip.date_from  }}</td>
                     <td>{{  trip.date_to  }}</td>
                     <td>{{  trip.description  }}</td>
                     <td><a href="{%  url 'schedules:leave_trip' id=trip.id %}"> Leave Trip</a></td>
                  </tr>
               {% endfor %}
            </tbody>
            </table>
            <br>
            <h4>Other User's Travel Plans:</h4>
            <table class="table table-striped">
               <thead>
                  <tr>
                     <th>Name</th>
                     <th>Destination</th>
                     <th>Travel Start Date</th>
                     <th>Travel End Date</th>
                     <th>Do You Want to Join?</th>
                  </tr>
               </thead>
               <tbody>
               {% for trip in other_trips %}
                  <tr>
                     <td>{{  trip.user_creator.name  }}</th>
                     <td><a href="{%  url 'schedules:destination' id=trip.id %}"> {{  trip.destination  }}</a></td>
                     <td>{{  trip.date_from  }}</td>
                     <td>{{  trip.date_to  }}</td>
                     <td><a href="{%  url 'schedules:join' id=trip.id  %}">Join</a></td>
                  </tr>
               {% endfor %}
            </tbody>
            </table>
         </div>
      </body>
      <footer>
            <a class="nav navbar-nav navbar-right" href="{% url 'schedules:add' %}">Add Travel Plan</a>
      </footer>
  </div>
</html>