main/apps/log_reg/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.log_reg.urls', namespace= 'users')),
    url(r'^travels/', include('apps.schedules.urls', namespace='schedules'))
]

main/apps/log_reg/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import bcrypt
import re
EMAIL_REGEX = re.compile (r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
name_regex = re.compile(r'^[a-zA-Z -]+[\s]+[a-zA-Z -]+$')

class UserManager(models.Manager):
    def valid_registration(self, user_info, request):
        print "Validating information for " + user_info['username']
        valid = True
        if not name_regex.match(user_info['name']):
            messages.warning(request, "Full names must be comprised of all letters, a space between first and last name, and no apostrophes!")
            valid = False
        if len(user_info['name']) < 3:
            messages.warning(request, "Full name must be 3 or more characters long!")
            valid = False
        if not EMAIL_REGEX.match(user_info['username']):
            messages.warning(request, "Email is not a valid email!")
            valid = False
        if len(user_info['username']) < 3:
            messages.warning(request, "Email should be at least 3 characters!")
            valid = False
        if len(user_info['password']) < 8:
            messages.warning(request, "Password is too short!")
            valid = False
        if user_info['password'] != user_info['confirm_password']:
            messages.warning(request, "Passwords do not match!")
            valid = False
        if User.objects.filter(username = user_info['username']):
            messages.error(request, "This username already exists!")
            valid = False
        if valid == True:
            print "Successful registration for " + user_info['username']
            hashed = bcrypt.hashpw(user_info['password'].encode(), bcrypt.gensalt())
            User.objects.create(name = request.POST['name'], username = request.POST['username'], password = hashed)
        return valid

    def login_user(self, user_info, request):
        print "Validating login information for " + user_info['username']
        valid = True
        if User.objects.filter(username = user_info['username']):
            hashed = User.objects.get(username = user_info['username']).password
            hashed = hashed.encode('utf-8')
            password = user_info['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
                print "Login successful for " + user_info['username']
                valid = True
            else:
                messages.warning(request, "Password does not match the one on file!")
                valid = False
        else:
            messages.warning(request, "Username does not match with one on file!")
            valid = False
        return valid

class User(models.Model):
    name = models.CharField(max_length=100)
    username = models.EmailField()
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __str__(self):
        return self.name

main/apps/log_reg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
    if 'name' not in request.session:
        return render(request, 'log_reg/index.html')
    else:
        return redirect(reverse('schedules:home'))

def register(request):
    if User.objects.valid_registration(request.POST, request):
        valid = True
        user = User.objects.get(username = request.POST['username'])
        request.session['name'] = user.name
        request.session['username'] = user.username
        request.session['user_id'] = user.id
        return redirect(reverse('schedules:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def login(request):
    if User.objects.login_user(request.POST, request):
        valid = True
        user = User.objects.get(username = request.POST['username'])
        request.session['name'] = user.name
        request.session['username'] = user.username
        request.session['user_id'] = user.id
        return redirect(reverse('schedules:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def logout(request):
    print "Logging off " + request.session['username']
    request.session.clear()
    return redirect(reverse('users:index'))

main/apps/log_reg/templates/log_reg/index.html
<!DOCTYPE html>
<html>
<head>
  <title>PY Belt</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'login/css/stylesheet.css' %}">
</head>

<body>
   <div class="container">
      <h1>Welcome!</h1>
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-info" role="alert">
             <p>{{  message  }}</p>
          </div>
          {% endfor %}
      {% endif %}


      <div class="row">
      <div class="col-md-6">

         <form class="" action="{% url 'users:registration' %}" method="POST">
            {% csrf_token %}

            <h2>Register</h2>
            <div class="form-group">
               <label for="name">Full Name</label>
               <input name="name" type="text" class="form-control" id="first_name" placeholder="Full Name">
            </div>

            <div class="form-group">
               <label for="exampleInputEmail1">Username</label>
               <input name="username" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>

            <div class="form-group">
               <label for="exampleInputPassword1">Password</label>
               <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>

            <p>*Password should be at least 8 characters.</p>

            <div class="form-group">
               <label for="exampleInputPassword2">Confirm PW</label>
               <input name="confirm_password" type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
            </div>
            <br>
            <button type="submit" name="register" class="btn btn-default">Register</button>
         </form>
      </div>

      <div class="col-md-6">

         <form class="" action="{% url 'users:login' %}" method="POST">
            <h2>Login</h2>
            {% csrf_token %}

            <div class="form-group">
               <label for="exampleInputEmail1">Username</label>
               <input name="username" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>

            <div class="form-group">
               <label for="exampleInputPassword1">Password</label>
               <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>

            <button type="submit" name="login" class="btn btn-default">Login</button>
        </form>
      </div>
   </div>

   </div>
</body>

</html>